version: '3.8'

services:
  video-render-api:
    build: .
    ports:
      - "8023:8023"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - API_KEY=${API_KEY:-change_me}
      - GDRIVE_SERVICE_ACCOUNT_JSON=${GDRIVE_SERVICE_ACCOUNT_JSON:-}
      - GENERIC_TIMEZONE=${TIMEZONE:-Europe/Madrid}
    volumes:
      # Solo para desarrollo local, quitar en producción
      - ./temp_videos:/app/temp_videos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8023/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
